"""Initial migration

Revision ID: 70442baa49a0
Revises: 
Create Date: 2025-05-27 12:59:33.923037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70442baa49a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newslettersubscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('newsletterservices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('newsletter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('payment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('asunto', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('enviado', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('newsletter_correo_key', type_='unique')
        batch_op.drop_column('correo')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivery_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('delivery_email', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('apellido', sa.String(length=120), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('delivery_email')
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('delivery_name')
        batch_op.drop_column('estado')

    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('newsletter_correo_key', ['correo'])
        batch_op.drop_column('enviado')
        batch_op.drop_column('asunto')
        batch_op.drop_column('titulo')

    op.drop_table('payment_items')
    op.drop_table('password_reset_tokens')
    op.drop_table('newsletterservices')
    op.drop_table('newslettersubscription')
    # ### end Alembic commands ###
